name: jaffle_shop_starrocks
version: '0.1'
profile: jaffle_shop_starrocks
config-version: 2
model-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
seed-paths:
  - data
macro-paths:
  - macros
target-path: target
clean-targets:
  - target
  - dbt_modules
  - logs
models:
  jaffle_shop_starrocks:
    materialized: table
    staging:
      materialized: view
quoting:
  database: false
  schema: false
  identifier: false
seeds:
  jaffle_shop_starrocks:
    raw_customers:
      +column_types:
        created: datetime
    raw_plan:
      +column_types:
        metadata: json
